name: Package and release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow for your own token, the name cannot start with "GITHUB_"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 20
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g retail
